use_frameworks!

platform :ios, '10.0'

target 'CosmosMobLogin_Example' do
  pod 'CosmosMobLogin', :path => '../'

  target 'CosmosMobLogin_Tests' do
    inherit! :search_paths

    
  end
  
  pod 'mob_secverify'
end
